// utils/strings.ts
export const STRINGS = {
  COMMON: {
    SELECT_LANGUAGE: 'Select Language',
    SAVE: 'Save',
    CLEAR: 'Clear',
    READ: 'Read',
    CANCEL: 'Cancel',
    EDIT: 'Edit',
    CONFIRM: 'Confirm',
    LOADING: 'Loading...',
    ERROR: 'Error',
    SUCCESS: 'Success',
    WARNING: 'Warning',

        // NEW ADDITIONS for loading states:
    PROCESSING: 'Processing...',
    PROCESSING_TEXT: 'Processing article content...',
    // LOADING: 'Loading...',
    LOADING_TEXT: 'Opening article...',
  },
  
  LANGUAGES: {
    CHINESE: 'Chinese',
    RUSSIAN: 'Russian',
    SPANISH: 'Spanish',
    FRENCH: 'French',
    GERMAN: 'German',
    ITALIAN: 'Italian',
    PORTUGUESE: 'Portuguese',
    JAPANESE: 'Japanese',
    KOREAN: 'Korean',
    ARABIC: 'Arabic',
    HINDI: 'Hindi',
    BENGALI: 'Bengali',
    HEBREW: 'Hebrew',
    GREEK: 'Greek',
    THAI: 'Thai',
    VIETNAMESE: 'Vietnamese',
    TURKISH: 'Turkish',
    DUTCH: 'Dutch',
    SWEDISH: 'Swedish',
    NORWEGIAN: 'Norwegian',
    DANISH: 'Danish',
    FINNISH: 'Finnish',
    POLISH: 'Polish',
    CZECH: 'Czech',
    HUNGARIAN: 'Hungarian',
    ROMANIAN: 'Romanian',
    BULGARIAN: 'Bulgarian',
    UKRAINIAN: 'Ukrainian',
    SERBIAN: 'Serbian',
    CROATIAN: 'Croatian',
    SLOVAK: 'Slovak',
    SLOVENIAN: 'Slovenian',
    LITHUANIAN: 'Lithuanian',
    LATVIAN: 'Latvian',
    ESTONIAN: 'Estonian',
    INDONESIAN: 'Indonesian',
    MALAY: 'Malay',
    FILIPINO: 'Filipino',
    SWAHILI: 'Swahili',
    PERSIAN: 'Persian',
    URDU: 'Urdu',
    UNKNOWN: 'Unknown Language',
  },
  
  SETTINGS: {
    TITLE: 'Settings',
    LANGUAGE: 'Language',
    THEME: 'Theme',
    FONT_SIZE: 'Font Size',
    ROMANIZATION: 'Romanization',
    PERFORMANCE: 'Performance',
    AUTO_SAVE: 'Auto Save',
    NOTIFICATIONS: 'Notifications',
    RESET: 'Reset to Defaults',
    EXPORT: 'Export Settings',
    IMPORT: 'Import Settings',
    SAVE: 'Save Settings',
    CANCEL: 'Cancel',
    
    THEME_OPTIONS: {
      LIGHT: 'Light',
      DARK: 'Dark',
      AUTO: 'Auto (System)',
    },
    
    ROMANIZATION_DESCRIPTION: 'Show romanization only on first occurrence of each word',
    PERFORMANCE_DESCRIPTION: 'Enable performance mode for faster processing (may use more memory)',
    AUTO_SAVE_DESCRIPTION: 'Automatically save changes',
    NOTIFICATIONS_DESCRIPTION: 'Show notifications for saved articles and errors',
  },

  INPUT_SCREEN: {
    SEARCH_LANGUAGES: 'Search languages...',
    LANGUAGES_COUNT: (filtered: number, total: number) => `${filtered} of ${total} languages`,
    NO_LANGUAGES_FOUND: (query: string) => `No languages found matching "${query}"`,
    ADD_TEXT_TO_ENABLE: (languageName: string) => `Add text in English or ${languageName} to enable reading`,
    ARTICLE_TITLE: 'Article Title',
    ENGLISH: 'English',
    TARGET_LANGUAGE: (languageName: string) => languageName,
    EXPAND: 'Expand',
    COLLAPSE: 'Collapse',
    PASTE_TEXT: 'Paste Text',
  },
  
  MODALS: {
    EDIT_TITLE: 'Edit Title',
    EDIT_ENGLISH: 'Edit English Text',
    EDIT_TARGET: (languageName: string) => `Edit ${languageName} Text`,
    SAVE_CHANGES: 'Save Changes',
    DISCARD_CHANGES: 'Discard Changes',
  },
  
  NOTIFICATIONS: {
    ARTICLE_SAVED: 'Article saved successfully!',
    SAVING_FAILED: 'Failed to save article. Please try again.',
    CLEAR_CONFIRMATION: 'Are you sure you want to clear all content? This cannot be undone.',
    CLEAR_CANCEL: 'Cancel',
    CLEAR_CONFIRM: 'Clear',
    PROCESSING_ERROR: 'Failed to process text. Please check your input and try again.',
  },
};